/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

int fibonacci(int n)
{
    if (n == 1) return 1;
    if (n == 2) return 2;
    return fibonacci(n-1)+ fibonacci(n-2);
}

int i = 1;
int f = fibonacci(i);
int sum = 0;

while (f < 4000000)
{
    if(f % 2 == 0)
    {
        sum += f;
    }
    i++;
    f = fibonacci(i);
}

Console.WriteLine(sum);